### ISSUE TITLE
signal SIGSEGV: segmentation violation when using LOBs parallel

### ISSUE THREAD

**Issue by travelliu** [godror/godror#297] opened 2023-06-20 03:59 UTC
**Describe the bug**

After connecting to the database, multiple goroutine to query. The query logic is as follows and appears

```go
conn,err := m.DB.Conn(ctx)
		if err != nil {
			t.Error(err)
			return
		}
		defer conn.Close()
		
		_,err = conn.ExecContext(ctx,"ALTER SESSION SET DB_FILE_MULTIBLOCK_READ_COUNT=128")
		if err != nil {
			t.Error(err)
			return
		}
		rows,err := conn.QueryContext(ctx,"select sysdate from dual");
		if err != nil {
			t.Error(err)
			return
		}
		defer rows.Close()
		for rows.Next() {
			var a1 string
			if err := rows.Scan(&a1); err != nil {
				t.Error(err)
				return
			}
			fmt.Println(a1)
		}
		if err := rows.Err(); err != nil {
			t.Error(err)
			return
		}
```

panic 

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x1015c3c9f]

runtime stack:
runtime.throw({0x101b5f2a2?, 0x42f1bed8002d00b6?})
        /usr/local/opt/go/libexec/src/runtime/panic.go:1047 +0x5d fp=0x7ff7bfefed30 sp=0x7ff7bfefed00 pc=0x10003c41d
runtime.sigpanic()
        /usr/local/opt/go/libexec/src/runtime/signal_unix.go:821 +0x3e9 fp=0x7ff7bfefed90 sp=0x7ff7bfefed30 pc=0x100053bc9

goroutine 3400 [syscall]:
runtime.cgocall(0x1015ac1b0, 0xc001da18a8)
        /usr/local/opt/go/libexec/src/runtime/cgocall.go:157 +0x5c fp=0xc001da1880 sp=0xc001da1848 pc=0x1000083fc
github.com/godror/godror._Cfunc_dpiConn_release(0x6000037040c0)
        _cgo_gotypes.go:2713 +0x48 fp=0xc001da18a8 sp=0xc001da1880 pc=0x100672d48
github.com/godror/godror.(*conn).closeNotLocking.func1(0xc001da1968?)
        /Users/travel/Documents/Code/go/pkg/mod/github.com/godror/godror@v0.36.0/conn.go:264 +0x3a fp=0xc001da18e0 sp=0xc001da18a8 pc=0x10067b59a
github.com/godror/godror.(*conn).closeNotLocking(0xc001488000)
        /Users/travel/Documents/Code/go/pkg/mod/github.com/godror/godror@v0.36.0/conn.go:264 +0x1dc fp=0xc001da19d8 sp=0xc001da18e0 pc=0x10067b51c
github.com/godror/godror.(*conn).Close(0xc001488000)
        /Users/travel/Documents/Code/go/pkg/mod/github.com/godror/godror@v0.36.0/conn.go:239 +0x85 fp=0xc001da1a28 sp=0xc001da19d8 pc=0x10067b265
database/sql.(*driverConn).finalClose.func2()
        /usr/local/opt/go/libexec/src/database/sql/sql.go:644 +0x3c fp=0xc001da1a50 sp=0xc001da1a28 pc=0x10057f3bc
database/sql.withLock({0x102392ce0, 0xc0005da090}, 0xc001da1af8)
        /usr/local/opt/go/libexec/src/database/sql/sql.go:3405 +0x8c fp=0xc001da1a90 sp=0xc001da1a50 pc=0x10058df8c
database/sql.(*driverConn).finalClose(0xc0005da090)
        /usr/local/opt/go/libexec/src/database/sql/sql.go:642 +0x116 fp=0xc001da1b38 sp=0xc001da1a90 pc=0x10057f276
database/sql.finalCloser.finalClose-fm()
        <autogenerated>:1 +0x2b fp=0xc001da1b50 sp=0xc001da1b38 pc=0x10058fa4b
database/sql.(*driverConn).Close(0xc0005da090)
        /usr/local/opt/go/libexec/src/database/sql/sql.go:623 +0x13f fp=0xc001da1b98 sp=0xc001da1b50 pc=0x10057f13f
database/sql.(*DB).putConn(0xc000ecc270, 0xc0005da090, {0x0, 0x0}, 0xb0?)
        /usr/local/opt/go/libexec/src/database/sql/sql.go:1484 +0x2e5 fp=0xc001da1c08 sp=0xc001da1b98 pc=0x100583625
database/sql.(*driverConn).releaseConn(...)
        /usr/local/opt/go/libexec/src/database/sql/sql.go:527
database/sql.(*Conn).close(0xc001ae8380?, {0x0, 0x0})
        /usr/local/opt/go/libexec/src/database/sql/sql.go:2096 +0xcf fp=0xc001da1c80 sp=0xc001da1c08 pc=0x1005875af
database/sql.(*Conn).Close(0xc001da1c70?)
        /usr/local/opt/go/libexec/src/database/sql/sql.go:2108 +0x1d fp=0xc001da1ca8 sp=0xc001da1c80 pc=0x10058771d

```

**To Reproduce**
At least the offending source code;
the best is a minimal test case that reproduces the error.

**Expected behavior**

**Error output**
Copy the error output (panic, stack trace),
or the output of running with `DPI_DEBUG_LEVEL=92`.

**Your oracle client version**
e.g. 12.2.0.1.0

**Your godror version**
e.g. v0.37.0

**Your go version**
e.g. 1.20.4

**Your gcc version**
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.5.0

**Machine (please complete the following information):**
 - OS: [e.g. win] macos
 - Architecture: [e.g. x86_64] x86_64
 - Version: [e.g. 10]  13.4

**Additional context**

**Comment by tgulacsi** [comment] 2023-06-20 05:35
I cannot reproduce it against a v19.19.0.0.0 AS SYSDBA, neither with current main, nor with v0.36.0.

How reproducible is this?
Against what database, with what client versions ?
OS, architecture, Go version?

**Comment by travelliu** [comment] 2023-06-20 06:10
i use 0.37.0 and 0.36.0 have this problem, rollback to. 0.34.0 no problem. 

```
user=system password=****** connectString="(DESCRIPTION=(CONNECT_TIMEOUT = 30)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=172.23.1.54)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=mtk)))"
configDir= connectionClass=godror enableEvents=0 externalAuth=0 heterogeneousPool=0
libDir= newPassword= noTimezoneCheck=0 poolIncrement=0 poolMaxSessions=100
poolMinSessions=0 poolSessionMaxLifetime=0s poolSessionTimeout=0s poolWaitTimeout=0s
prelim=0 standaloneConnection=1 sysasm=0 sysdba=0 sysoper=0 timezone=
```

Oracle 19.17.0.0.0 
go 1.20.4
macos 13.4

**Comment by tgulacsi** [comment] 2023-06-20 06:25
What if you skip the ALTER SESSION part?
What if you change only something hat don't harm? Like "ALTER SESSION SET SERIALIZATION_LEVEL = READ COMMITED" ?
I think that DB_FILE_MULTIBLOCK_READ_COUNT causes this SIGSEGV somehow, but don't know why, and we should eliminate/ensure this suspect first.
And you're the only one that test this...

**Comment by travelliu** [comment] 2023-06-20 06:29
> What if you skip the ALTER SESSION part?
> What if you change only something hat don't harm? Like "ALTER SESSION SET SERIALIZATION_LEVEL = READ COMMITED" ?
> I think that DB_FILE_MULTIBLOCK_READ_COUNT causes this SIGSEGV somehow, but don't know why, and we should eliminate/ensure this suspect first.
> And you're the only one that test this...

OK. i test it

**Comment by travelliu** [comment] 2023-06-20 06:48
use 0.37.0 and comment  alter session set DB_FILE_MULTIBLOCK_READ_COUNT have this problem @tgulacsi

**Comment by travelliu** [comment] 2023-06-20 06:54
Testing with 0.34.0 three times is fine 
Test with 0.37.0 three times, 1-2 times there is a problem

**Comment by tgulacsi** [comment] 2023-06-20 08:54
```go test -run=Issue297 -count=100```
does not reproduce it for me.

**Comment by travelliu** [comment] 2023-06-20 09:27
> Sorry, I don't understand. So,
> 
> * does it produce the error WITHOUT ANY alter session?
> * does it produce the error WITH alter session set serialization_level = read commited; ?
> * Or it errors ONLY with DB_FILE_MULTIBLOCK_READ_COUNT ?

Both comments and not comments DB_FILE_MULTIBLOCK_READ_COUNT  have this problem

**Comment by travelliu** [comment] 2023-06-20 09:49
DPI_DEBUG_LEVEL=92
Too many logs for concurrent execution of query database 
```
ODPI [14645] 2023-06-20 13:20:36.137: fn end dpiObjectType_getAttributes(0x7f978c0b50a0) -> 0
ODPI [14645] 2023-06-20 13:20:36.137: fn start dpiObjectAttr_getInfo(0x7f978c109240)
ODPI [14645] 2023-06-20 13:20:36.137: fn end dpiObjectAttr_getInfo(0x7f978c109240) -> 0
ODPI [14645] 2023-06-20 13:20:36.137: fn start dpiObjectType_getInfo(0x7f978c108940)
ODPI [14645] 2023-06-20 13:20:36.137: fn end dpiObjectType_getInfo(0x7f978c108940) -> 0
ODPI [14645] 2023-06-20 13:20:36.137: fn start dpiObjectType_getAttributes(0x7f978c108940)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectType_getAttributes(0x7f978c108940) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_getInfo(0x7f978c1b4ca0)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_getInfo(0x7f978c1b4ca0) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_getInfo(0x7f978c1b4d20)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_getInfo(0x7f978c1b4d20) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_getInfo(0x7f978c1b4da0)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_getInfo(0x7f978c1b4da0) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_getInfo(0x7f978c1b4e20)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_getInfo(0x7f978c1b4e20) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectType_addRef(0x7f978c108940)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectType_addRef(0x7f978c108940) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_getInfo(0x7f978c0b5250)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_getInfo(0x7f978c0b5250) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_getInfo(0x7f978c1089e0)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_getInfo(0x7f978c1089e0) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_getInfo(0x7f978c108a40)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_getInfo(0x7f978c108a40) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_getInfo(0x7f978c1b3bf0)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_getInfo(0x7f978c1b3bf0) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiStmt_fetchRows(0x7f978c0b4fe0)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiStmt_fetchRows(0x7f978c0b4fe0) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiVar_release(0x7f978c0b5140)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiVar_release(0x7f978c0b5140) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiVar_release(0x7f978c1087b0)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiVar_release(0x7f978c1087b0) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiStmt_release(0x7f978c0b4fe0)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiStmt_release(0x7f978c0b4fe0) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiStmt_release(0x7f978c0b4fe0)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiStmt_release(0x7f978c0b4fe0) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiConn_getIsHealthy(0x7f97ac10c2d0)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiConn_getIsHealthy(0x7f97ac10c2d0) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_release(0x7f978c1b4da0)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_release(0x7f978c1b4da0) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_release(0x7f978c1b4e20)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_release(0x7f978c1b4e20) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_release(0x7f978c1b4ca0)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_release(0x7f978c1b4ca0) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_release(0x7f978c1b4d20)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_release(0x7f978c1b4d20) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectType_release(0x7f978c108940)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectType_release(0x7f978c108940) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_release(0x7f978c108a40)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_release(0x7f978c108a40) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_release(0x7f978c1b3bf0)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_release(0x7f978c1b3bf0) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_release(0x7f978c109240)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_release(0x7f978c109240) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_release(0x7f978c0b5250)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_release(0x7f978c0b5250) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectAttr_release(0x7f978c1089e0)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectAttr_release(0x7f978c1089e0) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiObjectType_release(0x7f978c0b50a0)
ODPI [14645] 2023-06-20 13:20:36.138: fn end dpiObjectType_release(0x7f978c0b50a0) -> 0
ODPI [14645] 2023-06-20 13:20:36.138: fn start dpiConn_release(0x7f97ac10c2d0)
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x22453a2]
````

**Comment by travelliu** [comment] 2023-06-20 10:12
Set up xx DPI_DEBUG_LEVEL=92 to run the app 
[1.log.zip](https://github.com/godror/godror/files/11798781/1.log.zip)

**Comment by tgulacsi** [comment] 2023-06-20 12:19
Yes. I've tried to parallellize TestIssue297 without success (failure :)).
Please try to extend that test case till it fails, or try to create minimal reproducer code.

**Comment by tgulacsi** [comment] 2023-06-20 12:34
From the log I get that ALTER SESSION DB_FILE_MULTIBLOCK_READ_COUNT is set earlier, with success, no panic.
And it seems that all the tests pass (except that CreateIndex), and they Close cleanly.
Except goroutine 1394, which is stuck in dpiLob_readBytes.

So LOBs are involved. 
With LOBs, if you use them as Reader, use an sql.Tx and ExecContext / QueryContext - NEVER QueryRowContext. And don't use the Lob.Reader after rows.Close()   !

And make sure to not share Conn between goroutines.

**Comment by travelliu** [comment] 2023-06-20 14:15
> From the log I get that ALTER SESSION DB_FILE_MULTIBLOCK_READ_COUNT is set earlier, with success, no panic. And it seems that all the tests pass (except that CreateIndex), and they Close cleanly. Except goroutine 1394, which is stuck in dpiLob_readBytes.
> 
> So LOBs are involved. With LOBs, if you use them as Reader, use an sql.Tx and ExecContext / QueryContext - NEVER QueryRowContext. And don't use the Lob.Reader after rows.Close() !

lob use default string. 
no use QueryRowContext.

**Comment by tgulacsi** [comment] 2023-06-21 05:09
Line 75725 of your log says that there is a reading from a LOB still going when you Close everything.
Follow that stack trace to find where have you started that goroutine, and ensure that it's finished before you Close its connection.

**Comment by travelliu** [comment] 2023-06-21 06:18
Each goroutine handles one select
db.Conn()-> conn, 
conn.ExecContext(alter)
conn.QueryContext(sql)
rows.Scan()

If blob/clob/xml/udt appears, I will finish reading and process the next line.

rows.Close()
conn.Close()

Theoretically, reading LOB by one goroutine should not affect other goroutines

**Comment by tgulacsi** [comment] 2023-06-21 08:32
It may affect, if you do db.Close() when a goroutine lingers.

**Comment by travelliu** [comment] 2023-06-21 13:09
> It may affect, if you do db.Close() when a goroutine lingers.

db.Close() is executed after all goroutine are complete

**Closed** 2023-07-06 06:13 UTC
