### ISSUE TITLE
Connect a Go Program to Oracle Database using godror

### ISSUE THREAD

**Issue by kwx970125774** [godror/godror#46] opened 2020-04-16 14:09 UTC
I followed the link below to try to connect to the Oracle Database 12.2 using go and reported an error:
Error running query
username="scott" dsn="orcl" params={authMode:0 connectionClass:0x28087c0 connectionClassLength:6 purity:0 newPassword:<nil> newPasswordLength:0 appContext:<nil> numAppContext:0 externalAuth:0 externalHandle:<nil> pool:0x2808820 tag:<nil> tagLength:0 matchAnyTag:0 outTag:<nil> outTagLength:0 outTagFound:0 shardingKeyColumns:<nil> numShardingKeyColumns:0 superShardingKeyColumns:<nil> numSuperShardingKeyColumns:0 outNewSession:0}: ORA-00000: DPI-1012: proxy authentication is not possible with homogeneous pools

Link:
https://blogs.oracle.com/developers/how-to-connect-a-go-program-to-oracle-database-using-goracle

go demo:
`package main
  
import (
    "fmt"
    "database/sql"
    _ "github.com/godror/godror"
)
  
func main(){
  
    db, err := sql.Open("godror", "scott/tiger@orcl")
    if err != nil {
        fmt.Println(err)
        return
    }
    defer db.Close()
      
      
    rows,err := db.Query("select sysdate from dual")
    if err != nil {
        fmt.Println("Error running query")
        fmt.Println(err)
        return
    }
    defer rows.Close()
  
    var thedate string
    for rows.Next() {
  
        rows.Scan(&thedate)
    }
    fmt.Printf("The date is: %s\n", thedate)
}`

Oracle Client version:18.3.0.0.0
Oracle Database version: 12.2.0.1.0
godror version:v0.14.0
go version:1.14.2
gcc version:gcc-4.8.5-39.0.3.el7.x86_64

OS: Linux 
Architecture:3.10.0-693.el7.x86_64
Version:Red Hat Enterprise Linux Server release 7.4 (Maipo)

**Comment by tgulacsi** [comment] 2020-04-16 14:21
You can try the current master, the connection code has been rewritten, but I'm dubious: this should just work.

What if you connect to "oracle://scott:tiger@orcl?standaloneConnection=1" ?

**Comment by Letarg** [comment] 2020-04-16 15:10
Same problem here. Just updated to 0.14 and got this error.
Adding "standaloneConnection=1"  to connection string doesnt work either.

**Comment by anthony-tuininga** [comment] 2020-04-16 15:24
Interesting! I tried with 0.14 and master a few times and didn't notice any problems. I just tried it again and got the error you are getting. Let me see if I can figure out why that is and get back to you.

**Comment by anthony-tuininga** [comment] 2020-04-16 15:36
@tgulacsi, the problem was introduced in the changes you made after you merged my pull request. Specifically, I had deliberately used pointers for the connection and pool parameter structures. A pool parameters pointer of nil indicated that a standalone connection should be used. You modified that to check that all parameters are empty with the function IsZero(). Unfortunately, in the connection parameters parsing code you are setting BOTH the pool parameters and the connection parameters! So standalone connections will never be created. And since connection parameters are also specified, you'll get an attempt at proxy authentication -- which is not permissible with homogeneous pools (the default). Take a look [here](https://github.com/godror/godror/blob/master/drv.go#L731) and [here](https://github.com/godror/godror/blob/master/drv.go#L758).

**Comment by tgulacsi** [comment] 2020-04-16 16:31
Thanks @anthony-tuininga !

But @kwx970125774 this is only on the master branch, v0.14.0 - I haven't tagged the rewritten (and it seems to be buggy) code yet!

**Comment by kwx970125774** [comment] 2020-04-17 00:45
> You can try the current master, the connection code has been rewritten, but I'm dubious: this should just work.

**Comment by kwx970125774** [comment] 2020-04-17 00:47
> You can try the current master, the connection code has been rewritten, but I'm dubious: this should just work.
> 
> What if you connect to "oracle://scott:tiger@orcl?standaloneConnection=1" ?

Thanks a lot, this problem has been solved.

**Comment by kwx970125774** [comment] 2020-04-17 00:48
> You can try the current master, the connection code has been rewritten, but I'm dubious: this should just work.
> 
> What if you connect to "oracle://scott:tiger@orcl?standaloneConnection=1" ?

**Comment by tgulacsi** [comment] 2020-04-17 05:09
Ok, I've eliminated the UserName, Password, DSN, Timezone doubling with ConnParams/PoolParams, now we have one source of truth, and all tests pass.

So @kwx970125774 please test with the current master if possible, and report back!
If it still fails with your original connection string, then we have to reproduce it somehow.

Thanks in advance!

**Comment by tgulacsi** [comment] 2020-04-20 18:53
Hi, 
@kwx970125774 can you test the current master, please? I'd love to tag is as v0.15.0, but I want to have it working!

**Closed** 2020-06-10 11:11 UTC

**Comment by josejuanmontiel** [comment] 2022-12-22 08:58
Yes i know... (sorry for write in close issue) but if someone reach here with a "ORA-12637: Packet receive failed" and testing to Oracle XE 21 (or other) in Docker... disable out-of-band breaks usage by setting DISABLE_OOB=ON in sqlnet.ora (client and/or server) as said [here](https://franckpachot.medium.com/19c-instant-client-and-docker-1566630ab20e) ...

**Comment by firdavstoshev** [comment] 2025-03-28 19:39
@tgulacsi how to connect to oracle with proxy using godror driver?
