### ISSUE TITLE
Error when result set has TimeStamp (DateTime)  in the record set.

### ISSUE THREAD

**Issue by vkarmendra** [godror/godror#98] opened 2020-09-11 16:26 UTC
When the ref cursor dataset has timestamp getting below error

panic: time: missing Location in call to Date

goroutine 1 [running]:
time.Date(0x7e4, 0x8, 0x19, 0x9, 0xd, 0x35, 0x0, 0x0, 0x4cf0f2, 0xc0000ca000, ...)
        c:/go/src/time/time.go:1368 +0x633
github.com/godror/godror.(*rows).Next(0xc0000e0240, 0xc00011e600, 0x5e, 0x5e, 0xc0000e0240, 0xc000099ea8)
        C:/Users/vishwa.karmendra/go/src/github.com/godror/godror/rows.go:451 +0x10e3
main.main()
        C:/DockerFiles/db.go:124 +0x6d8
exit status 2

**Expected behavior**
It should parse the date and return it.

**Your oracle client version**
ODAC 12.2c

**Your godror version**
latest

**Your go version**
1.13.5

**Your gcc version**
9.2.0

**Machine (please complete the following information):**
 - OS: [win]
 - Architecture [x64]
 - Version: [10]

**Comment by tgulacsi** [comment] 2020-09-11 18:51
Can you show a minimal example, a reproducing SELECT?

What's your local (where you run your client program) timezone?
What's the database's timezone?

(Both are printed when you start `go test github.com/godror/godror` with GODROR_TEST_DB, GODROR_TEST_USERNAME, GODROR_TEST_PASSWORD environment variables set).

**Comment by tgulacsi** [comment] 2020-09-11 18:52
If you can add a test case to `TestTsTZ` in `z_test.go`, that'd be wonderful!

**Comment by vkarmendra** [comment] 2020-09-13 16:47
Hi @tgulacsi 

I am using below code

```
query := `
	DECLARE
	ID NUMBER;
	RECORD_DATA SYS_REFCURSOR;
  BEGIN
	ID := 233445;
	  
	PKG_V2.PRC_GET_DATA(
	  ID => ID,
	  RECORD_DATA => RECORD_DATA
	);
	
	
	:1 := RECORD_DATA;
   
	
  END;
  `
  
  var rows1 driver.Rows
	_, err = db.ExecContext(ctx, query, sql.Out{Dest: &rows1})
	if err != nil {
		fmt.Println("Error running query")
		fmt.Println(err)
		return

	}
	defer rows1.Close()
	cols1 := rows1.(driver.RowsColumnTypeScanType).Columns()
	values := make([]driver.Value, len(cols1))

	for {
		if err = rows1.Next(values); err != nil {
			if err == io.EOF {
				break
			}
		}
		fmt.Println(values)
	}

```

Local timezone: Local
Database timezone: UTC

**Comment by vkarmendra** [comment] 2020-09-13 19:41
Getting below error while running the tests. I think because of extra **\r** in the user and password field. Is it because I am running it one windows machine. Not able to find from where that extra \r is coming.

```
export TNS_ADMIN=C:\Users\vishwa.karmendra\go\src\github.com\godror\godror\contrib\free.db
export GODROR_TEST_USERNAME=system
export GODROR_TEST_PASSWORD=*******
export GODROR_TEST_DB=localhost:1521/ORCLCDB
export GODROR_TEST_STANDALONE=1
# GODROR_TEST_STANDALONE is not set, using default false
# user="system\r" password="SECRET-7eIvgbCeHoA=" connectString="localhost:1521/ORCLCDB\r"
configDir=C:\Users\VISHWA~1.KAR\AppData\Local\Temp\godror_drv_test-665742151
connectionClass=TestClassName enableEvents=1 heterogeneousPool=0 libDir= poolIncrement=2
poolMaxSessions=16 poolMinSessions=2 poolSessionMaxLifetime=5m0s poolSessionTimeout=1m0s
poolWaitTimeout=5s prelim=0 standaloneConnection=0 sysasm=0 sysdba=0 sysoper=0
timezone=local
Version: v0.20.1
panic: params=user="system\r" password="SECRET-7eIvgbCeHoA=" connectString="localhost:1521/ORCLCDB\r"
configDir=C:\Users\VISHWA~1.KAR\AppData\Local\Temp\godror_drv_test-665742151
enableEvents=1 timezone=local poolIncrement=2 poolMaxSessions=16 poolMinSessions=2 poolSessionMaxLifetime=5m0s
poolSessionTimeout=1m0s poolWaitTimeout=5s extAuth=0: ORA-01017: invalid username/password; logon denied

goroutine 1 [running]:
github.com/godror/godror_test.init.0()
        C:/Users/vishwa.karmendra/go/src/github.com/godror/godror/z_test.go:199 +0x24c2
exit status 2
FAIL    github.com/godror/godror        2.069s
```

**Comment by tgulacsi** [comment] 2020-09-13 19:58
What does ```PKG_V2.PRC_GET_DATA(
	  ID => ID,
	  RECORD_DATA => RECORD_DATA
	);``` return in `RECORD_DATA` ? 
What types?
What SELECT could be an example for it?

I'm trying to find out which branch fails in rows.go#L448.

**Comment by vkarmendra** [comment] 2020-09-14 13:02
What does PKG_V2.PRC_GET_DATA( ID => ID, RECORD_DATA => RECORD_DATA ); return in RECORD_DATA ? --> Yes, that's correct.
What types? -> Didn't understand this. Its SYS_REFCURSOR only while fetching the data we get the column types. This is working when I am fetching the refcursor not having any timestamp.

**Comment by tgulacsi** [comment] 2020-09-14 14:37
An example for such a timestamp is what I ask for.

**Comment by tgulacsi** [comment] 2020-09-14 14:50
PTAL 29a9a9e TestTsRset - I cannot reproduce the error.
That's why I'm asking for a concrete example of your cursor, data type - a DUMP could help, too!

**Comment by zhy233** [comment] 2020-09-15 08:51
I have the same problem as you. The initTz method is called during statement preprocessing and statement execution. But this problem arises when you pull a value of a time type from a cursor. Before rows.Next(r) is executed, the closeNotLocking method has c.params.timezone set to nil. So when the Next method calls the TimeZone() method internally, the c.params.timezone fetched is always nil

**Comment by tgulacsi** [comment] 2020-09-15 08:55
But why is closeNotLocking called when the Row is still in use? 
You have to keep it alive by preparing the statement on a Tx (or Conn), and closing it only after you've processed its rows!

**Comment by zhy233** [comment] 2020-09-15 09:24
The closeNotLocking method is not executed because conn calls the Close() method, but because the validateConnection method in database/sql calls the IsValid() method implemented in godror, which calls the closeNotLocking method.

**Comment by tgulacsi** [comment] 2020-09-15 10:41
But validateConnection is only called in putConn, which is called when *unused* the connection is put back to the pool.
So you must have freed it beforehand - or didn't pin it.

That's why I say first Prepare a *Stmt, and Close that only after you're finished with your result sets.

**Comment by vkarmendra** [comment] 2020-09-15 11:05
Hi @tgulacsi 

Please use the below query to reproduce the issue.

DECLARE
  v_cur SYS_REFCURSOR;
BEGIN
  OPEN v_cur FOR
  	SELECT TO_DATE('2015/05/15 8:30:25', 'YYYY/MM/DD HH:MI:SS') as DD FROM DUAL
	UNION ALL SELECT TO_DATE('2015/05/15 8:30:25', 'YYYY/MM/DD HH:MI:SS') as DD FROM DUAL;
  :1 := v_cur;
END;

**Comment by tgulacsi** [comment] 2020-09-15 12:10
@vkarmendra thanks, these are not TIMESTAMPs, but DATEs, but with this I can reproduce the error on pooled connection.

Ok, so a workaround is to use an *sql.Tx or *sql.Conn, ExecContext on that - this pins the connection.

A solution (I'm a little bit hesitant about this) is to leave c.params.Timestamp as is - see @d5888ef

**Closed** 2020-09-15 12:10 UTC

**Comment by vkarmendra** [comment] 2020-09-15 16:38
Thanks, It worked.

**Comment by zhy233** [comment] 2020-09-16 02:34
Nice!
